// background-daemon: persistent autofarm loop with Android boot-start.
// - Schedules a periodic farm cycle via setInterval (in-process).
// - Installs a Termux:Boot script so the loop resumes on phone restart.
// - Logs PID + heartbeat to ~/.nexus/autofarm/daemon.json.
// - Graceful shutdown on SIGTERM / SIGINT.

import fs from "node:fs"
import path from "node:path"
import os from "node:os"
import { execFile, spawn } from "node:child_process"
import { promisify } from "node:util"
import { log } from "./logger.ts"

const execFileAsync = promisify(execFile)

const DAEMON_STATE = path.join(os.homedir(), ".nexus", "autofarm", "daemon.json")
const TERMUX_BOOT_DIR = "/data/data/com.termux/files/home/.termux/boot"
const BOOT_SCRIPT = path.join(TERMUX_BOOT_DIR, "nexus-autofarm.sh")

let loopHandle: ReturnType<typeof setInterval> | null = null
let running = false
let onCycle: (() => Promise<void>) | null = null
let intervalMs = 5 * 60_000 // 5 min default
let lastHeartbeat = 0

export interface DaemonState {
  pid: number
  startedAt: string
  lastHeartbeat: string
  cycleCount: number
  intervalMs: number
  enabled: boolean
}

function readState(): DaemonState | null {
  try {
    if (!fs.existsSync(DAEMON_STATE)) return null
    return JSON.parse(fs.readFileSync(DAEMON_STATE, "utf8")) as DaemonState
  } catch {
    return null
  }
}

function writeState(s: DaemonState): void {
  try {
    fs.mkdirSync(path.dirname(DAEMON_STATE), { recursive: true })
    const tmp = DAEMON_STATE + ".tmp"
    fs.writeFileSync(tmp, JSON.stringify(s, null, 2))
    fs.renameSync(tmp, DAEMON_STATE)
  } catch (e) {
    log.warn("daemon", `writeState failed: ${(e as Error).message}`)
  }
}

function beat(): void {
  lastHeartbeat = Date.now()
  const s = readState()
  if (s) {
    s.lastHeartbeat = new Date(lastHeartbeat).toISOString()
    writeState(s)
  }
}

async function runOneCycle(): Promise<void> {
  if (running) {
    log.debug("daemon", "cycle already in progress, skipping")
    return
  }
  running = true
  const t0 = Date.now()
  try {
    if (onCycle) {
      await onCycle()
    } else {
      log.warn("daemon", "no cycle handler registered")
    }
    const s = readState()
    if (s) {
      s.cycleCount = (s.cycleCount ?? 0) + 1
      writeState(s)
    }
    log.info("daemon", `cycle ok in ${Date.now() - t0}ms`)
  } catch (e) {
    log.error("daemon", `cycle failed: ${(e as Error).message}`)
  } finally {
    running = false
  }
}

export function startDaemon(opts: { intervalMs?: number; cycle: () => Promise<void> }): DaemonState {
  intervalMs = opts.intervalMs ?? intervalMs
  onCycle = opts.cycle
  if (loopHandle) {
    log.info("daemon", "already running, updating interval")
    clearInterval(loopHandle)
  }
  const state: DaemonState = {
    pid: process.pid,
    startedAt: new Date().toISOString(),
    lastHeartbeat: new Date().toISOString(),
    cycleCount: 0,
    intervalMs,
    enabled: true,
  }
  writeState(state)
  loopHandle = setInterval(() => {
    runOneCycle().catch((e) => log.error("daemon", (e as Error).message))
  }, intervalMs)
  // Graceful shutdown
  const stop = () => {
    if (loopHandle) {
      clearInterval(loopHandle)
      loopHandle = null
    }
    const s = readState()
    if (s) {
      s.enabled = false
      writeState(s)
    }
    log.info("daemon", "stopped")
    process.exit(0)
  }
  process.once("SIGTERM", stop)
  process.once("SIGINT", stop)
  log.info("daemon", `started (pid ${process.pid}, interval ${intervalMs}ms)`)
  return state
}

export function stopDaemon(): void {
  if (loopHandle) {
    clearInterval(loopHandle)
    loopHandle = null
  }
  const s = readState()
  if (s) {
    s.enabled = false
    writeState(s)
  }
  log.info("daemon", "stopped")
}

export function daemonStatus(): DaemonState | null {
  return readState()
}

export async function runOneNow(): Promise<void> {
  await runOneCycle()
}

/** Install a Termux:Boot script so the daemon auto-resumes on phone restart.
 *  Requires `pkg install termux-boot-api` once. */
export async function installBootScript(): Promise<{ ok: boolean; path: string; reason?: string }> {
  try {
    fs.mkdirSync(TERMUX_BOOT_DIR, { recursive: true })
    // The boot script spawns the autofarm start command detached.
    const script = `#!/data/data/com.termux/files/usr/bin/bash
# Auto-generated by NEXUS autofarm daemon
# Restarts the autofarm loop on phone boot.
LOG="${os.homedir()}/.nexus/autofarm/boot.log"
mkdir -p "$(dirname "$LOG")"
{
  echo "[boot] $(date) restarting NEXUS autofarm daemon"
  if command -v nexus >/dev/null 2>&1; then
    nohup nexus autofarm start 300000 > "$LOG" 2>&1 &
    echo "[boot] pid=$!"
  else
    echo "[boot] nexus CLI not on PATH"
  fi
} >> "$LOG" 2>&1
`
    fs.writeFileSync(BOOT_SCRIPT, script, { mode: 0o755 })
    return { ok: true, path: BOOT_SCRIPT }
  } catch (e) {
    return { ok: false, path: BOOT_SCRIPT, reason: (e as Error).message }
  }
}

export async function uninstallBootScript(): Promise<void> {
  try {
    if (fs.existsSync(BOOT_SCRIPT)) fs.unlinkSync(BOOT_SCRIPT)
  } catch (e) {
    log.warn("daemon", `uninstall failed: ${(e as Error).message}`)
  }
}

export function bootScriptPath(): string {
  return BOOT_SCRIPT
}

export { beat as heartbeat }
