// Free provider catalog for the autofarm plugin.
// These are providers that officially offer free daily tiers.
// We never store secrets; we only drive the public signup flow.

import type { FreeProvider } from "./types.ts"

export const FREE_PROVIDERS: FreeProvider[] = [
  {
    name: "fireworks_ai",
    label: "Fireworks AI",
    freeTier: true,
    freePerDay: 500000,
    url: "https://fireworks.ai/dashboard/api-keys",
    baseUrl: "https://api.fireworks.ai/inference/v1",
    models: ["fireworks/llama-v3-1-70b-instruct", "fireworks/llama-v3-8b-instruct", "fireworks/mixtral-8x7b-instruct"],
    maxKeys: 3,
    signupUrl: "https://fireworks.ai/register",
    signupFields: { email: "email", password: "password", name: "name", org: "org" },
    notes: "Google sign-up is also supported; we prefer email sign-up for full automation.",
  },
  {
    name: "together_ai",
    label: "Together AI",
    freeTier: true,
    freePerDay: 500000,
    url: "https://api.together.ai/settings/api-keys",
    baseUrl: "https://api.together.xyz/v1",
    models: ["mistralai/mixtral-8x7b-instruct", "meta-llama/llama-3-70b-chat-hf"],
    maxKeys: 3,
    signupUrl: "https://api.together.ai/signup",
    signupFields: { email: "email", password: "password", name: "name" },
  },
  {
    name: "mistral",
    label: "Mistral",
    freeTier: true,
    freePerDay: 500000,
    url: "https://console.mistral.ai/api-keys/",
    baseUrl: "https://api.mistral.ai/v1",
    models: ["mistral-large-latest", "mistral-small-latest", "open-mistral-7b"],
    maxKeys: 3,
    signupUrl: "https://console.mistral.ai/login",
    signupFields: { email: "email", password: "password", name: "name" },
  },
  {
    name: "anthropic",
    label: "Anthropic",
    freeTier: true,
    freePerDay: 500000,
    url: "https://console.anthropic.com/settings/keys",
    baseUrl: "https://api.anthropic.com/v1",
    models: ["claude-3-5-sonnet-latest", "claude-3-haiku-20240307"],
    maxKeys: 3,
    signupUrl: "https://console.anthropic.com/signup",
    signupFields: { email: "email", password: "password", name: "name" },
    notes: "Often requires email verification before API key page is reachable.",
  },
  {
    name: "xai",
    label: "xAI (Grok)",
    freeTier: true,
    freePerDay: 500000,
    url: "https://console.x.ai/",
    baseUrl: "https://api.x.ai/v1",
    models: ["grok-beta", "grok-vision-beta"],
    maxKeys: 3,
    signupUrl: "https://console.x.ai/register",
    signupFields: { email: "email", password: "password", name: "name" },
  },
  {
    name: "cohere",
    label: "Cohere",
    freeTier: true,
    freePerDay: 500000,
    url: "https://dashboard.cohere.com/api-keys",
    baseUrl: "https://api.cohere.com/v1",
    models: ["command-r-plus", "command-light", "command-r"],
    maxKeys: 3,
    signupUrl: "https://dashboard.cohere.com/signup",
    signupFields: { email: "email", password: "password", name: "name" },
  },
  {
    name: "perplexity",
    label: "Perplexity",
    freeTier: true,
    freePerDay: 500000,
    url: "https://platform.perplexity.ai/",
    baseUrl: "https://api.perplexity.ai/v1",
    models: ["llama-3.1-sonar-small-128k-online", "llama-3.1-sonar-large-128k-online"],
    maxKeys: 3,
    signupUrl: "https://www.perplexity.ai/register",
    signupFields: { email: "email", password: "password", name: "name" },
  },
  {
    name: "replicate",
    label: "Replicate",
    freeTier: true,
    freePerDay: 50000,
    url: "https://replicate.com/account/api-tokens",
    baseUrl: "https://api.replicate.com/v1",
    models: ["meta/llama-3-70b-instruct"],
    maxKeys: 3,
    signupUrl: "https://replicate.com/signup",
    signupFields: { email: "email", password: "password", name: "username" },
    notes: "Free tier has low token budget; only farm when demand is low.",
  },
  {
    name: "huggingface",
    label: "HuggingFace",
    freeTier: true,
    freePerDay: 500000,
    url: "https://huggingface.co/settings/tokens",
    baseUrl: "https://api-inference.huggingface.co/models",
    models: ["meta-llama/Llama-3-70b-chat-hf", "mistralai/Mistral-7B-Instruct-v0.3"],
    maxKeys: 5,
    signupUrl: "https://huggingface.co/join",
    signupFields: { email: "email", password: "password", name: "fullname", org: "orgname" },
  },
  {
    name: "groq",
    label: "Groq",
    freeTier: true,
    freePerDay: 500000,
    url: "https://console.groq.com/keys",
    baseUrl: "https://api.groq.com/openai/v1",
    models: ["llama-3.1-70b-versatile", "llama-3.1-8b-instant", "mixtral-8x7b-32768"],
    maxKeys: 3,
    signupUrl: "https://console.groq.com/signup",
    signupFields: { email: "email", password: "password", name: "name" },
  },
  {
    name: "openrouter",
    label: "OpenRouter (free tier)",
    freeTier: true,
    freePerDay: 200000,
    url: "https://openrouter.ai/settings/keys",
    baseUrl: "https://openrouter.ai/api/v1",
    models: [":free", "meta-llama/llama-3.1-8b-instruct:free"],
    maxKeys: 5,
    signupUrl: "https://openrouter.ai/signup",
    signupFields: { email: "email", password: "password", name: "name" },
    notes: "Has many free-tier models; excellent fallback.",
  },
  {
    name: "cerebras",
    label: "Cerebras",
    freeTier: true,
    freePerDay: 1000000,
    url: "https://cloud.cerebras.ai/",
    baseUrl: "https://api.cerebras.ai/v1",
    models: ["llama-3.1-70b", "llama-3.1-8b"],
    maxKeys: 3,
    signupUrl: "https://cloud.cerebras.ai/register",
    signupFields: { email: "email", password: "password", name: "name" },
  },
  {
    name: "deepseek",
    label: "DeepSeek",
    freeTier: true,
    freePerDay: 500000,
    url: "https://platform.deepseek.com/api_keys",
    baseUrl: "https://api.deepseek.com/v1",
    models: ["deepseek-chat", "deepseek-coder"],
    maxKeys: 3,
    signupUrl: "https://platform.deepseek.com/signup",
    signupFields: { email: "email", password: "password", name: "name" },
  },
]

export function getProvider(name: string): FreeProvider | undefined {
  return FREE_PROVIDERS.find((p) => p.name === name)
}