import path from "path"
import { Style, Icon } from "../core/style"

const EOL = "\n"
import type { NexusPlugin, PluginContext } from "../core/types"

interface Template {
  id: string
  match: RegExp
  description: string
  files: Record<string, string>
}

const TEMPLATES: Template[] = [
  {
    id: "node-api",
    match: /(?:node|express|api|backend|rest)/i,
    description: "Node.js + Express REST API",
    files: {
      "package.json": `{
  "name": "{{name}}",
  "version": "1.0.0",
  "type": "module",
  "main": "src/index.js",
  "scripts": {
    "start": "node src/index.js",
    "dev": "node --watch src/index.js"
  },
  "dependencies": {
    "express": "^4.19.2"
  }
}
`,
      "src/index.js": `import express from "express"

const app = express()
app.use(express.json())

app.get("/", (_req, res) => res.json({ ok: true, service: "{{name}}" }))

app.get("/api/items", (_req, res) => res.json([]))

app.post("/api/items", (req, res) => res.status(201).json(req.body))

const port = process.env.PORT || 3000
app.listen(port, () => console.log("{{name}} listening on port " + port))
`,
      ".env.example": `PORT=3000
DATABASE_URL=
`,
      "README.md": `# {{name}}

Express REST API generated by NEXUS.

\`\`\`bash
npm install
npm run dev
\`\`\`
`,
      ".gitignore": "node_modules/\n.env\ndist/\n",
    },
  },
  {
    id: "react",
    match: /(?:react|frontend|portfolio|ui|website)/i,
    description: "React + Vite frontend app",
    files: {
      "package.json": `{
  "name": "{{name}}",
  "private": true,
  "version": "1.0.0",
  "type": "module",
  "scripts": {
    "dev": "vite",
    "build": "vite build",
    "preview": "vite preview"
  },
  "dependencies": {
    "react": "^18.3.1",
    "react-dom": "^18.3.1"
  },
  "devDependencies": {
    "@vitejs/plugin-react": "^4.3.1",
    "vite": "^5.4.0"
  }
}
`,
      "index.html": `<!doctype html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>{{name}}</title>
  </head>
  <body>
    <div id="root"></div>
    <script type="module" src="/src/main.jsx"></script>
  </body>
</html>
`,
      "vite.config.js": `import { defineConfig } from "vite"
import react from "@vitejs/plugin-react"

export default defineConfig({ plugins: [react()] })
`,
      "src/main.jsx": `import React from "react"
import ReactDOM from "react-dom/client"
import App from "./App"

ReactDOM.createRoot(document.getElementById("root")).render(<App />)
`,
      "src/App.jsx": `export default function App() {
  return (
    <main style={{ fontFamily: "system-ui", padding: "2rem" }}>
      <h1>{{name}}</h1>
      <p>Scaffolded by NEXUS. Start building!</p>
    </main>
  )
}
`,
      "README.md": `# {{name}}

React + Vite app generated by NEXUS.

\`\`\`bash
npm install
npm run dev
\`\`\`
`,
      ".gitignore": "node_modules/\ndist/\n.env\n",
    },
  },
  {
    id: "php-login",
    match: /(?:php|mysql)\s*(?:\+\s*)?(?:login|auth)?|login\s*(?:system)?\s*(?:with)?\s*mysql/i,
    description: "PHP + MySQL login system",
    files: {
      "config/db.php": `<?php
$host = getenv('DB_HOST') ?: 'localhost';
$db   = getenv('DB_NAME') ?: 'app_db';
$user = getenv('DB_USER') ?: 'root';
$pass = getenv('DB_PASS') ?: '';

try {
    $pdo = new PDO("mysql:host=$host;dbname=$db;charset=utf8mb4", $user, $pass, [
        PDO::ATTR_ERRMODE => PDO::ERRMODE_EXCEPTION,
        PDO::ATTR_DEFAULT_FETCH_MODE => PDO::FETCH_ASSOC,
    ]);
} catch (PDOException $e) {
    http_response_code(500);
    exit('Database connection failed');
}
`,
      "schema.sql": `CREATE DATABASE IF NOT EXISTS app_db CHARACTER SET utf8mb4;
USE app_db;

CREATE TABLE IF NOT EXISTS users (
    id INT AUTO_INCREMENT PRIMARY KEY,
    email VARCHAR(255) NOT NULL UNIQUE,
    password_hash VARCHAR(255) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
`,
      "register.php": `<?php
require __DIR__ . '/config/db.php';

if ($_SERVER['REQUEST_METHOD'] === 'POST') {
    $email = filter_var($_POST['email'] ?? '', FILTER_VALIDATE_EMAIL);
    $password = $_POST['password'] ?? '';
    if (!$email || strlen($password) < 8) {
        $error = 'Valid email and 8+ character password required';
    } else {
        $hash = password_hash($password, PASSWORD_DEFAULT);
        $stmt = $pdo->prepare('INSERT INTO users (email, password_hash) VALUES (?, ?)');
        try {
            $stmt->execute([$email, $hash]);
            header('Location: login.php?registered=1');
            exit;
        } catch (PDOException) {
            $error = 'Email already registered';
        }
    }
}
?>
<!doctype html>
<html><body>
<h1>Register</h1>
<?php if (!empty($error)) echo '<p>' . htmlspecialchars($error) . '</p>'; ?>
<form method="post">
  <input type="email" name="email" placeholder="Email" required>
  <input type="password" name="password" placeholder="Password" required minlength="8">
  <button type="submit">Register</button>
</form>
<a href="login.php">Login</a>
</body></html>
`,
      "login.php": `<?php
session_start();
require __DIR__ . '/config/db.php';

if ($_SERVER['REQUEST_METHOD'] === 'POST') {
    $stmt = $pdo->prepare('SELECT * FROM users WHERE email = ?');
    $stmt->execute([$_POST['email'] ?? '']);
    $user = $stmt->fetch();
    if ($user && password_verify($_POST['password'] ?? '', $user['password_hash'])) {
        session_regenerate_id(true);
        $_SESSION['user_id'] = $user['id'];
        header('Location: dashboard.php');
        exit;
    }
    $error = 'Invalid credentials';
}
?>
<!doctype html>
<html><body>
<h1>Login</h1>
<?php if (!empty($error)) echo '<p>' . htmlspecialchars($error) . '</p>'; ?>
<form method="post">
  <input type="email" name="email" placeholder="Email" required>
  <input type="password" name="password" placeholder="Password" required>
  <button type="submit">Login</button>
</form>
<a href="register.php">Register</a>
</body></html>
`,
      "dashboard.php": `<?php
session_start();
if (empty($_SESSION['user_id'])) {
    header('Location: login.php');
    exit;
}
?>
<!doctype html>
<html><body><h1>Dashboard</h1><p>Welcome, user #<?= (int) $_SESSION['user_id'] ?></p>
<a href="logout.php">Logout</a></body></html>
`,
      "logout.php": `<?php
session_start();
session_destroy();
header('Location: login.php');
`,
      "README.md": "# {{name}}\n\nPHP + MySQL login system generated by NEXUS.\n\n1. Import schema.sql into MySQL\n2. Copy .env.example values or set DB_* environment variables\n3. Serve with: php -S localhost:8000\n",
      ".gitignore": ".env\nconfig/.env\n",
    },
  },
  {
    id: "static",
    match: /.*/,
    description: "Static HTML site",
    files: {
      "index.html": `<!doctype html>
<html lang="en">
<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>{{name}}</title>
  <style>
    body { font-family: system-ui, sans-serif; margin: 0; min-height: 100vh; display: grid; place-items: center; background: #0f172a; color: #e2e8f0; }
    main { text-align: center; padding: 2rem; }
    h1 { font-size: 2.5rem; margin-bottom: .5rem; }
  </style>
</head>
<body>
  <main>
    <h1>{{name}}</h1>
    <p>Generated by NEXUS</p>
  </main>
</body>
</html>
`,
      "README.md": "# {{name}}\n\nStatic site generated by NEXUS.\n",
    },
  },
]

async function generate(ctx: PluginContext): Promise<number | void> {
  const query = ctx.args.join(" ")
  if (!query) {
    ctx.err("Usage: nexus code generate \"<description>\" --out ./dir")
    return 1
  }
  const outFlag = typeof ctx.flags.out === "string" ? ctx.flags.out : undefined
  const name = slug(query)
  const outDir = path.resolve(ctx.cwd, outFlag ?? `./${name}`)

  const template = TEMPLATES.find((t) => t.match.test(query)) ?? TEMPLATES[TEMPLATES.length - 1]
  const template_ = template as Template

  ctx.out(`${Icon.brain} Template: ${Style.TEXT_HIGHLIGHT}${template_.id}${Style.TEXT_NORMAL} (${template_.description})`)
  ctx.out(`${Icon.rocket} Generating at ${outDir}`)

  const fs = await import("fs/promises")
  const existing = await outputDirectoryIsEmpty(outDir)
  if (!existing.empty && ctx.flags.force !== true) {
    ctx.err(`Refusing to overwrite non-empty directory: ${outDir}`)
    ctx.out(`Re-run with --force only after reviewing the files that will be replaced.`)
    return 1
  }
  await fs.mkdir(outDir, { recursive: true })

  for (const [relPath, content] of Object.entries(template_.files)) {
    const target = path.join(outDir, relPath)
    await fs.mkdir(path.dirname(target), { recursive: true }).catch(() => {})
    await fs.writeFile(target, content.replaceAll("{{name}}", name))
    ctx.out(`  ${Icon.success} ${relPath}`)
  }

  ctx.out(`${EOL}${Icon.success} Project created: ${Style.TEXT_SUCCESS_BOLD}${outDir}${Style.TEXT_NORMAL}`)
}

export async function outputDirectoryIsEmpty(target: string): Promise<{ empty: boolean; exists: boolean }> {
  try {
    const fs = await import("fs/promises")
    const entries = await fs.readdir(target)
    return { empty: entries.length === 0, exists: true }
  } catch (error) {
    if ((error as NodeJS.ErrnoException).code === "ENOENT") return { empty: true, exists: false }
    throw error
  }
}

function slug(input: string): string {
  return input
    .toLowerCase()
    .replace(/[^a-z0-9\s-]/g, "")
    .trim()
    .split(/\s+/)
    .slice(0, 4)
    .join("-") || "nexus-project"
}

async function dockerize(ctx: PluginContext): Promise<number | void> {
  const target = path.resolve(ctx.cwd, ctx.args[0] ?? ".")
  const fs = await import("fs/promises")
  let entries: string[] = []
  try {
    entries = await fs.readdir(target)
  } catch {
    ctx.err(`Directory not found: ${target}`)
    return 1
  }

  const dockerfile = entries.includes("package.json")
    ? `FROM node:20-alpine
WORKDIR /app
COPY package*.json ./
RUN npm ci --omit=dev
COPY . .
EXPOSE 3000
CMD ["npm", "start"]
`
    : entries.includes("composer.json")
      ? `FROM php:8.3-apache
COPY . /var/www/html/
EXPOSE 80
`
      : entries.includes("requirements.txt")
        ? `FROM python:3.12-slim
WORKDIR /app
COPY requirements.txt .
RUN pip install -r requirements.txt
COPY . .
CMD ["python", "main.py"]
`
        : undefined

  if (!dockerfile) {
    ctx.err("Could not detect project type (looked for package.json, composer.json, requirements.txt)")
    return 1
  }

  await fs.writeFile(path.join(target, "Dockerfile"), dockerfile)
  await fs.writeFile(
    path.join(target, ".dockerignore"),
    "node_modules\n.git\ndist\nbuild\n.env\n",
  )
  ctx.out(`${Icon.success} Dockerfile + .dockerignore written to ${target}`)
}

async function serve(ctx: PluginContext): Promise<number | void> {
  const port = String(ctx.flags.port ?? 3000)
  const target = path.resolve(ctx.cwd, ctx.args[0] ?? ".")
  const proc = Bun.spawn(["python3", "-m", "http.server", port], {
    cwd: target,
    stdout: "inherit",
    stderr: "inherit",
  })
  ctx.out(`${Icon.info} Serving ${target} at ${Style.TEXT_HIGHLIGHT_BOLD}http://localhost:${port}${Style.TEXT_NORMAL} (Ctrl+C to stop)`)
  await proc.exited
}

async function convert(ctx: PluginContext): Promise<number | void> {
  const mod = await import("./translator")
  const translator = mod.default as NexusPlugin
  const translate = translator.commands.find((c) => c.name === "translate")
  if (!translate) {
    ctx.err("Translator plugin unavailable")
    return 1
  }
  ctx.out(`${Icon.info} Delegating to translator plugin...`)
  return translate.run(ctx)
}

async function composeAndCI(ctx: PluginContext): Promise<number | void> {
  const target = path.resolve(ctx.cwd, ctx.args[0] ?? ".")
  const fs = await import("fs/promises")
  if (!(await Bun.file(path.join(target, "Dockerfile")).exists())) {
    await dockerize({ ...ctx, args: [target] })
  }
  await fs.writeFile(
    path.join(target, "docker-compose.yml"),
    `services:\n  app:\n    build: .\n    ports:\n      - "3000:3000"\n    env_file:\n      - .env\n    restart: unless-stopped\n`,
  )
  await fs.mkdir(path.join(target, ".github", "workflows"), { recursive: true })
  await fs.writeFile(
    path.join(target, ".github", "workflows", "ci.yml"),
    `name: CI\non:\n  push:\n    branches: [main]\n  pull_request:\n\njobs:\n  build:\n    runs-on: ubuntu-latest\n    steps:\n      - uses: actions/checkout@v4\n      - uses: actions/setup-node@v4\n        with:\n          node-version: 20\n      - run: npm ci || npm install\n      - run: npm test --if-present\n      - run: npm run build --if-present\n`,
  )
  ctx.out(`${Icon.success} docker-compose.yml + GitHub Actions CI generated in ${target}`)
}

const plugin: NexusPlugin = {
  name: "codegen",
  version: "0.1.0",
  description: "Generate, convert, dockerize and serve projects locally",
  tags: ["code", "generate", "scaffold", "docker"],
  commands: [
    {
      name: "generate",
      describe: 'generate a new project from a description, e.g. nexus code generate "react portfolio" --out ./portfolio',
      usage: 'nexus code generate "<description>" [--out ./dir]',
      run: generate,
    },
    {
      name: "dockerize",
      describe: "detect project type and write Dockerfile + .dockerignore",
      usage: "nexus code dockerize ./my-project",
      run: dockerize,
    },
    {
      name: "serve",
      describe: "serve a directory over local HTTP",
      usage: "nexus code serve [dir] --port 3000",
      run: serve,
    },
    {
      name: "convert",
      describe: "convert code between languages/frameworks (translator bridge)",
      usage: "nexus code convert --from js --to ts ./src",
      run: convert,
    },
    {
      name: "containerize",
      describe: "Dockerfile + docker-compose + GitHub Actions CI, full stack",
      usage: "nexus code containerize ./my-project",
      run: composeAndCI,
    },
  ],
}

export default plugin

export * as CodegenPlugin from "./codegen"
