import path from "path"
import { Style, Icon } from "../core/style"
import type { NexusPlugin, PluginContext } from "../core/types"

const LANGUAGE_MAP: Record<string, { ext: string; runtime: string }> = {
  python: { ext: ".py", runtime: "python3" },
  nodejs: { ext: ".js", runtime: "node" },
  typescript: { ext: ".ts", runtime: "bun" },
  php: { ext: ".php", runtime: "php" },
  go: { ext: ".go", runtime: "go run" },
}

const FRAMEWORK_HINTS: Array<[RegExp, string]> = [
  [/express/i, "Express.js"],
  [/fastify/i, "Fastify"],
  [/flask|fastapi|django/i, "Python web framework"],
  [/laravel|symfony/i, "PHP framework"],
  [/react.*vue|vue/i, "Vue"],
  [/css.*tailwind|tailwind/i, "Tailwind CSS"],
  [/jest.*vitest|vitest/i, "Vitest"],
]

async function translate(ctx: PluginContext): Promise<number | void> {
  const fromIdx = ctx.args.indexOf("--from")
  const toIdx = ctx.args.indexOf("--to")
  const target =
    ctx.args.find((a, i) => !a.startsWith("--") && ctx.args[i - 1] !== "--from" && ctx.args[i - 1] !== "--to") ?? "."
  const from = fromIdx >= 0 ? ctx.args[fromIdx + 1] : undefined
  const to = toIdx >= 0 ? ctx.args[toIdx + 1] : undefined

  if (!from || !to) {
    ctx.err('Usage: nexus translate --from <lang> --to <lang> [path]')
    return 1
  }

  const resolved = path.resolve(ctx.cwd, target)
  const stat = await import("fs/promises").then((fs) => fs.stat(resolved))
  const files = stat.isDirectory()
    ? await collectFiles(resolved, from)
    : [resolved]

  if (files.length === 0) {
    ctx.err(`No ${from} files found in ${resolved}`)
    return 1
  }

  const framework = FRAMEWORK_HINTS.find(([re]) => re.test(`${from} ${to}`))?.[1]
  ctx.out(`${Icon.brain} NEXUS Code Translator`)
  ctx.out(`  ${Style.TEXT_DIM}${from} → ${to}${framework ? ` (${framework})` : ""} — ${files.length} file(s)${Style.TEXT_NORMAL}`)

  if (!ctx.llm) {
    ctx.out("")
    ctx.out(`${Icon.warn} No LLM client connected — AI translation needs a configured model.`)
    ctx.out(`${Style.TEXT_DIM}Connect one with 'nexus api add' then retry, or use codegen templates:${Style.TEXT_NORMAL}`)
    ctx.out(`  nexus code generate "${to} version of this project" --out ./translated`)
    for (const file of files.slice(0, 10)) {
      ctx.out(`    ${Style.TEXT_DIM}${path.relative(ctx.cwd, file)}${Style.TEXT_NORMAL}`)
    }
    return 1
  }

  const outDir = path.resolve(ctx.cwd, typeof ctx.flags.out === "string" ? ctx.flags.out : "./translated")
  await import("fs/promises").then((fs) => fs.mkdir(outDir, { recursive: true }))

  for (const file of files) {
    const source = await Bun.file(file).text()
    const relPath = path.relative(resolved, file)
    ctx.out(`  ${Icon.rocket} ${relPath}`)
    const result = await ctx.llm.generate(
      `Translate this ${from} code to ${to}. Reply with ONLY the translated code, no markdown fences.\n\n${source}`,
    )
    const clean = result.replace(/^```[a-z]*\n?/m, "").replace(/\n?```$/m, "")
    const targetExt = LANGUAGE_MAP[to]?.ext ?? path.extname(file)
    const outPath = path.join(outDir, relPath.replace(/\.[^.]+$/, "") + targetExt)
    await import("fs/promises").then((fs) => fs.mkdir(path.dirname(outPath), { recursive: true }))
    await Bun.write(outPath, clean)
  }

  await Bun.write(
    path.join(outDir, "TRANSLATION_GUIDE.md"),
    `# Translation Guide (${from} → ${to})\n\nGenerated by NEXUS on ${new Date().toISOString()}\nReview all files manually — automated translation requires human verification.\n`,
  )
  ctx.out(`${Icon.success} Translated project written to ${outDir}`)
}

async function collectFiles(dir: string, lang: string): Promise<string[]> {
  const ext = LANGUAGE_MAP[lang?.toLowerCase()]?.ext
  if (!ext) return []
  const glob = new Bun.Glob(`**/*${ext}`)
  const matches: string[] = []
  for await (const match of glob.scan({ cwd: dir, dot: false })) {
    if (!match.includes("node_modules")) matches.push(path.join(dir, match))
  }
  return matches
}

const plugin: NexusPlugin = {
  name: "translator",
  version: "0.1.0",
  description: "AI code translation between languages and frameworks",
  tags: ["convert", "migrate", "translate"],
  commands: [
    {
      name: "translate",
      describe: "translate code between languages, e.g. nexus translate --from python --to nodejs ./script.py",
      usage: "nexus translate --from <lang> --to <lang> [path] [--out ./dir]",
      run: translate,
    },
  ],
}

export default plugin

export * as TranslatorPlugin from "./translator"
